### ISSUE TITLE
Fix stock entry form for "out" entries

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#10]
In the stock entry form, when "Out" is selected, remove border, supplier and carrier info fields and show fields "Buyer name" and "Buyer contact".

New form will look like this:
![image](https://user-images.githubusercontent.com/16163320/219985662-1750435a-bd52-44ca-a4ad-db7de30e70e9.png)
![image](https://user-images.githubusercontent.com/16163320/219985773-c33bf2d5-6e9d-4ed7-8aee-79c1cf27e62e.png)

**Comment by protibimbok** [comment]
![image](https://user-images.githubusercontent.com/33311165/220097244-fd4d3ca5-bfa0-4be3-a94e-228817c6a605.png)

Is this okay for the logs table?

**Comment by permafrost06** [comment]
Actually, now I'm thinking maybe we could just rename "Supplier Name" to "Supplier/Buyer Name" and "Supplier Contact" to "Supplier/Buyer Contact". If it's "In", we know it's supplier, and if it's "Out", we know it's buyer. Does that seem intuitive to you?

**Comment by protibimbok** [comment]
Yes, that would be more meaningful. Should I do this then?

**Comment by permafrost06** [comment]
Yeah go ahead

**Comment by protibimbok** [comment]
Any suggestions for naming supplier/buyer column?

**Comment by permafrost06** [comment]
Use something logical

**Comment by protibimbok** [comment]
Trader?

**Comment by permafrost06** [comment]
Merchant sounds better.

**Comment by protibimbok** [comment]
Okay
