### ISSUE TITLE
Attachment and Remarks for Stock Status

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#11]
Add columns for "Attachment" and "Remarks" in the Stock Status table. If there is no attachement or remark, user can add them. Note that these attachments and remarks are separate from the ones in the log. Ask questions if confused.

**Comment by protibimbok** [comment]
Should I use modal to give the option of uploading/editing these fields?

**Comment by permafrost06** [comment]
Yes, use a modal

**Comment by protibimbok** [comment]
What are the supported file types for attachment?

**Comment by permafrost06** [comment]
> What are the supported file types for attachment?

`.jpg`, `.jpeg`, `.png`, `.pdf` will be enough for now.
