### ISSUE TITLE
Make attachment modal larger

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#19]
> Make the modal larger. It takes up less than 30% of the viewport on my 1080p monitor.

How about 70% height of the screen?
![image](https://user-images.githubusercontent.com/33311165/220831219-3cfb45ba-bdef-4558-8dc5-0cd54faa8a6d.png)

_Originally posted by @protibimbok in https://github.com/permafrost06/sharee-sales/issues/16#issuecomment-1441250351_
 
 70% height is good. Also, make it at least 50% width.

**Comment by protibimbok** [comment]
You may delete this issue. It has been fixed in #16

**Comment by permafrost06** [comment]
The fix implemented in #16 is not good enough. It does not account for width. Also, it has to be done for each modal individually. I think it's better if we fix this in the modal's CSS.

**Comment by permafrost06** [comment]
I'll take care of this one.
