### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#2]
Remove all dead code: commented out code, unused functions, controllers, classes, imports, unused GitHub action, test etc.

**Comment by protibimbok** [comment]
Does that include Dockerfile & package.json?

**Comment by permafrost06** [comment]
> Does that include Dockerfile & package.json?

If they're being used, they should be kept. Why do we have a package.json? I didn't run any `npm`/`yarn` commands to run the project...

**Comment by protibimbok** [comment]
> > Does that include Dockerfile & package.json?
> 
> If they're being used, they should be kept. Why do we have a package.json? I didn't run any `npm`/`yarn` commands to run the project...

I have kept the **package.json** file because we might need this in future.

**Comment by permafrost06** [comment]
> > > Does that include Dockerfile & package.json?
> > 
> > 
> > If they're being used, they should be kept. Why do we have a package.json? I didn't run any `npm`/`yarn` commands to run the project...
> 
> I have kept the **package.json** file because we might need this in future.

Let’s remove it for now. Add it back when relevant.

**Comment by protibimbok** [comment]
It's done...
