### ISSUE TITLE
Fix stock issue: out quantity cannot be more than available quantity

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#26]
The shop cannot sell an item if they don't have it. Currently, negative stock is allowed, which is not possible irl. It can be fixed as below.

When a new entry is submitted,
- if it is of type "out", check if an "in" entry for that `item_id` exists:
  - if not, then show error "Item {{item_code}} not in stock"
  - if it exists, check the current quantity of the item `(total "in" quantity - total "out" quantity)`:
    - if the submitted quantity is larger than the current quantity, show error "Invalid quantity, {{current_quantity}} item {{item_code}} available in stock"

Allow otherwise

**Comment by protibimbok** [comment]
![image](https://user-images.githubusercontent.com/33311165/221387896-24707813-c194-44ee-a75e-996223d50ed4.png)

This is the error message

**Comment by permafrost06** [comment]
> ![image](https://user-images.githubusercontent.com/33311165/221387896-24707813-c194-44ee-a75e-996223d50ed4.png)
> 
> This is the error message

This is still a little vague. The software may be used by people with limited technical knowledge. I think being a bit more direct would be better in this case.

Something like: "Out quantity ({{quantity}}) higher than available quantity ({{available_quantity}}) for Item Code {{item_code}}"
For example: Out quantity (50) cannot be higher than available quantity (30) for Item Code 1003.

What do you think?

**Comment by protibimbok** [comment]
Okay. This is more descriptive
