### ISSUE TITLE
Finalize dev environment

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/sharee-sales#3]
A suitable dev environment should be decided and used to avoid issues.

The current readme should be replaced with instructions to set up this project.

**Comment by permafrost06** [comment]
The client currently has the project running locally in laragon but has plans to move to an online server

**Comment by protibimbok** [comment]
Laravel has a built-in dev server for testing & debugging. I keep mentioning XAMPP because in windows it's difficult to set up PHP, Mysql and other services. In XAMPP you get all of these together. But in an online server there is in most of the cases a way of installing Laravel app directly which does not depend on the development environment.

**Comment by permafrost06** [comment]
I think it may be better to move to docker. We're thinking of moving to a linode server. We'll add CI/CD to the project when we go online. Do you see any problems with that @protibimbok?

**Comment by protibimbok** [comment]
No, I don't have any problem at all. Laravel already has a built-in way of integrating docker. It's called **Laravel sail**, I'll add this in the project. Is that okay?

**Comment by permafrost06** [comment]
Okay, add Laravel sail and update the instructions. PR when done.

**Comment by permafrost06** [comment]
Perhaps for now, we could set up a github action to SSH into our cloud VM, clone this repo and publish changes. This will only be for a development version of the app.

We have to figure out how we want to push production changes.

**Comment by permafrost06** [comment]
Update the readme to serve the app with `php artisan serve`

**Comment by permafrost06** [comment]
We may soon be restarting this project from scratch - I've spoken to the client. A brand new codebase will allow us to move much faster and may also bring costs down. It means there is a possibility that we may be moving away from laravel. Until that decision is final - whether or not we're going to be using laravel for the long run - we shouldn't waste much time trying to automate deployment

**Comment by permafrost06** [comment]
If we decide to use docker in the future, this issue may be re-opened
